name = "overreacted"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 可选：添加 KV 命名空间，用于缓存
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<部署后从 Cloudflare 控制台获取>" 

[site]
bucket = "./out" 